version: '3.5'

include:
  - ${DOCKER_NETWORKS}

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app-${PROJECT_NAME}
    restart: ${RESTART_POLICY}
    environment:
      FPM_RUN_USER: ${FPM_RUN_USER}
      FPM_RUN_GROUP: ${FPM_RUN_GROUP}
      TZ: ${TZ}
      OPCACHE_MEMORY_CONSUMPTION: ${OPCACHE_MEMORY_CONSUMPTION}
      OPCACHE_INTERNED_STRINGS_BUFFER: ${OPCACHE_INTERNED_STRINGS_BUFFER}
      OPCACHE_MAX_ACCELERATED_FILES: ${OPCACHE_MAX_ACCELERATED_FILES}
      OPCACHE_REVALIDATE_FREQ: ${OPCACHE_REVALIDATE_FREQ}
      OPCACHE_ENABLE: ${OPCACHE_ENABLE}
      OPCACHE_ENABLE_CLI: ${OPCACHE_ENABLE_CLI}
      JIT_BUFFER_SIZE: ${JIT_BUFFER_SIZE}
    volumes:
      - ./app:/app
      - ./docker/config/php/custom-app.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      mysql:
        condition: service_healthy
    external_links:
      - redmine
    networks:
      - default
      - redmine

  mysql:
    image: mysql:8.0.30
    container_name: mysql-${PROJECT_NAME}
    restart: ${RESTART_POLICY}
    command:
      --collation-server=utf8_unicode_ci
      --init-connect='SET NAMES utf8'
      --character-set-server=utf8
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
      --default_time_zone="+03:00"
      --innodb_flush_method=O_DIRECT
      --innodb_flush_log_at_trx_commit=2
      --transaction-isolation=READ-COMMITTED
      --innodb_buffer_pool_size=56M
      --innodb_strict_mode=OFF
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql
      - ./docker/config/mysql:/docker-entrypoint-initdb.d
    networks:
      - default
      - redmine
    healthcheck:
      test: ["CMD", "mysql", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "use ${MYSQL_DATABASE}; show tables;"]
      interval: 5s
      retries: 50
      
  redmine:
    image: redmine:5.1.3
    container_name: redmine-${PROJECT_NAME}
    restart: ${RESTART_POLICY}
    ports:
      - 8080:3000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: ${MYSQL_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET}
    networks:
      - default
      - redmine