services:
  nginx:
    image: nginx:1.17.1-alpine
    container_name: nginx-${PROJECT_NAME}
    restart: ${RESTART_POLICY}
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./app/:/app/
    environment:
      TZ: ${TZ}
    networks:
      - default
      - redmine
    ports:
      - ${NGINX_PORT}:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${PROJECT_NAME}
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      -  ${PMA_PORT}:80
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default
      - redmine

networks:
  default:
  redmine:
    driver: bridge